AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Exclude:
    - spec/support/*.rb
    - lib/what/migrations/*.rb

Metrics/MethodLength:
  Max: 25
