AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Exclude:
    - spec/support/*.rb
    - lib/what/migrations/*.rb

Style/AccessModifierDeclarations:
  EnforcedStyle: 'inline'
