version: 2
jobs:
  build:
    working_directory: ~/what
    docker:
      - image: ruby:2.4.1
        environment:
          PGDATABASE: what_test
          PGUSER: what
          PGPASSWORD: password
          PGHOST: localhost
      - image: postgres:9.6.3
        environment:
          POSTGRES_DB: what_test
          POSTGRES_USER: what
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          key: gemfile-lock-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install --deployment
      - save_cache:
          key: gemfile-lock-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run: bundle exec rubocop
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec ruby spec/prepare.rb
      - run: bundle exec rspec
      - run: ADAPTER=sequel bundle exec rspec
