version: 2
jobs:
  build:
    working_directory: ~/what
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGDATABASE: what_test
          PGUSER: what
          PGPASSWORD: password
          PGHOST: localhost
      - image: postgres:9.6.3
        environment:
          POSTGRES_DB: what_test
          POSTGRES_USER: what
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run: bundle check || bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec ruby spec/prepare.rb
      - run: bundle exec rspec
      - run: ADAPTER=sequel bundle exec rspec

      - run: bundle exec rubocop
