version: 2
jobs:
  build:
    working_directory: ~/what
    docker:
      - image: ruby:2.4.1
        environment:
          PGDATABASE: what_test
          PGUSER: ubuntu
          PGPASSWORD: password
          PGHOST: localhost
      - image: postgres:9.6.3
        environment:
          POSTGRES_DB: what_test
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          key: gemfile-lock-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install --deployment
      - save_cache:
          key: gemfile-lock-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: wait for database
          command: |
            TIMEOUT=5
            until psql -h $PGHOST -U $PGUSER -d $PGDATABASE -c "select 1" > /dev/null 2>&1 || [ $TIMEOUT -eq 0 ]; do
              echo "Waiting for postgres server, $((TIMEOUT--)) remaining attempts..."
              sleep 1
            done
      - run: bundle exec ruby spec/prepare.rb
      - run: bundle exec rspec
