name: what

on: [push, pull_request]

jobs:
  ci_with_rails_version:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        rails: [5, 6]

    steps:
    - uses: actions/checkout@master

    - name: Runs code QA and tests
      run: docker-compose run -e RAILS_VERSION='~> ${{ matrix.rails }}' gem
